import type { User, Item } from './types';

const users: User[] = [
  {
    id: 'user-1',
    username: 'JaneDoe',
    profilePicture: 'user-1',
    city: 'San Francisco, CA',
    bio: 'Fashion lover with a passion for vintage finds. Selling pieces from my personal collection. Happy to chat!',
    emailVerified: true,
  },
  {
    id: 'user-2',
    username: 'JohnSmith',
    profilePicture: 'user-2',
    city: 'New York, NY',
    bio: 'Minimalist style enthusiast. All items are high-quality and well-cared for.',
    emailVerified: false,
  },
  {
    id: 'user-3',
    username: 'EmilyWhite',
    profilePicture: 'user-3',
    city: 'London, UK',
    bio: 'Eco-conscious seller. Join me in making fashion more sustainable!',
    emailVerified: true,
  },
];

const items: Item[] = [
  {
    id: 'item-1',
    title: 'Vintage Denim Jacket',
    description: 'A classic 80s denim jacket with unique patches. Perfectly worn-in and comfortable. A true statement piece.',
    category: 'Outerwear',
    condition: 'Gently used',
    size: 'M',
    tags: ['vintage', 'denim', '80s'],
    location: 'San Francisco, CA',
    images: ['item-1'],
    price: 75,
    priceType: 'Fixed',
    sellerId: 'user-1',
    createdAt: '2023-10-01T12:00:00Z',
  },
  {
    id: 'item-2',
    title: 'Floral Summer Dress',
    description: 'Light and airy floral dress, perfect for summer days. Features an adjustable waist tie and a beautiful pattern.',
    category: 'Dresses',
    condition: 'Like new',
    size: 'S',
    tags: ['summer', 'floral', 'dress'],
    location: 'New York, NY',
    images: ['item-2'],
    price: 45,
    priceType: 'Fixed',
    sellerId: 'user-2',
    createdAt: '2023-10-02T14:30:00Z',
  },
  {
    id: 'item-3',
    title: 'Leather Ankle Boots',
    description: 'Stylish and durable leather ankle boots. A versatile addition to any wardrobe. Only worn a few times.',
    category: 'Shoes',
    condition: 'Like new',
    size: '8',
    tags: ['boots', 'leather', 'shoes'],
    location: 'London, UK',
    images: ['item-3'],
    price: 120,
    priceType: 'Fixed',
    sellerId: 'user-3',
    createdAt: '2023-10-03T10:00:00Z',
  },
  {
    id: 'item-4',
    title: 'Striped Cotton T-Shirt',
    description: 'A simple and soft striped t-shirt made from 100% organic cotton. A wardrobe essential.',
    category: 'Tops',
    condition: 'Gently used',
    size: 'L',
    tags: ['cotton', 'basic', 't-shirt'],
    location: 'New York, NY',
    images: ['item-4'],
    price: 0,
    priceType: 'Free',
    sellerId: 'user-2',
    createdAt: '2023-10-04T09:00:00Z',
  },
  {
    id: 'item-5',
    title: 'High-Waisted Skinny Jeans',
    description: 'Comfortable and flattering high-waisted skinny jeans in a dark wash. Great for any season.',
    category: 'Bottoms',
    condition: 'Used',
    size: '28',
    tags: ['jeans', 'denim', 'high-waist'],
    location: 'San Francisco, CA',
    images: ['item-5'],
    price: 30,
    priceType: 'Fixed',
    sellerId: 'user-1',
    createdAt: '2023-10-05T18:00:00Z',
  },
  {
    id: 'item-6',
    title: 'Wool Knit Sweater',
    description: 'Cozy and warm wool knit sweater in a beautiful oatmeal color. Perfect for fall and winter.',
    category: 'Tops',
    condition: 'Gently used',
    size: 'M',
    tags: ['sweater', 'wool', 'cozy'],
    location: 'London, UK',
    images: ['item-6'],
    price: 50,
    priceType: 'Trade',
    sellerId: 'user-3',
    createdAt: '2023-10-06T11:45:00Z',
  },
  {
    id: 'item-7',
    title: 'Canvas Tote Bag',
    description: 'Durable canvas tote bag with a minimalist design. Ideal for groceries, books, or daily essentials.',
    category: 'Accessories',
    condition: 'New with tags',
    size: 'One Size',
    tags: ['bag', 'tote', 'canvas'],
    location: 'New York, NY',
    images: ['item-7'],
    price: 20,
    priceType: 'Fixed',
    sellerId: 'user-2',
    createdAt: '2023-10-07T16:20:00Z',
  },
  {
    id: 'item-8',
    title: 'Vintage Cat-Eye Sunglasses',
    description: 'Authentic 1960s cat-eye sunglasses. A rare find! Comes with the original case. Some minor wear consistent with age.',
    category: 'Accessories',
    condition: 'Used',
    size: 'One Size',
    tags: ['vintage', 'sunglasses', '60s'],
    location: 'San Francisco, CA',
    images: ['item-8'],
    price: 95,
    priceType: 'Fixed',
    sellerId: 'user-1',
    createdAt: '2023-10-08T13:00:00Z',
  },
  {
    id: 'item-9',
    title: 'Pleated A-Line Skirt',
    description: 'Chic pleated A-line skirt in a muted green. Falls just below the knee. Made from a high-quality crepe fabric.',
    category: 'Bottoms',
    condition: 'Like new',
    size: 'S',
    tags: ['skirt', 'pleated', 'green'],
    location: 'London, UK',
    images: ['item-9'],
    price: 40,
    priceType: 'Fixed',
    sellerId: 'user-3',
    createdAt: '2023-10-09T13:00:00Z',
  },
   {
    id: 'item-10',
    title: 'Classic Trench Coat',
    description: 'Timeless double-breasted trench coat. A perfect transitional piece for spring and autumn.',
    category: 'Outerwear',
    condition: 'Gently used',
    size: 'M',
    tags: ['trench', 'coat', 'classic'],
    location: 'New York, NY',
    images: ['item-10'],
    price: 150,
    priceType: 'Fixed',
    sellerId: 'user-2',
    createdAt: '2023-10-10T13:00:00Z',
  },
  {
    id: 'item-11',
    title: 'Minimalist White Sneakers',
    description: 'Clean and simple white sneakers that go with everything. Made from vegan leather.',
    category: 'Shoes',
    condition: 'Like new',
    size: '9',
    tags: ['sneakers', 'white', 'vegan'],
    location: 'San Francisco, CA',
    images: ['item-11'],
    price: 60,
    priceType: 'Fixed',
    sellerId: 'user-1',
    createdAt: '2023-10-11T13:00:00Z',
  },
  {
    id: 'item-12',
    title: 'Leather Crossbody Bag',
    description: 'Soft black leather crossbody bag with silver hardware. Perfect size for your phone, wallet, and keys.',
    category: 'Accessories',
    condition: 'Gently used',
    size: 'One Size',
    tags: ['bag', 'leather', 'crossbody'],
    location: 'London, UK',
    images: ['item-12'],
    price: 80,
    priceType: 'Trade',
    sellerId: 'user-3',
    createdAt: '2023-10-12T13:00:00Z',
  }
];

// Simulate a database query
export const getItems = async (): Promise<Item[]> => {
  return Promise.resolve(items);
};

export const getItem = async (id: string): Promise<Item | undefined> => {
  return Promise.resolve(items.find(item => item.id === id));
};

export const getUsers = async (): Promise<User[]> => {
  return Promise.resolve(users);
}

export const getUser = async (identifier: string): Promise<User | undefined> => {
  return Promise.resolve(users.find(user => user.username.toLowerCase() === identifier.toLowerCase() || user.id === identifier));
}

export const getItemsBySeller = async (sellerId: string): Promise<Item[]> => {
    return Promise.resolve(items.filter(item => item.sellerId === sellerId));
}
